### PR TITLE
[ARO-4744] CARRY: Do not run platform validation on an ARO cluster

### PR DESCRIPTION
**Pull request by hawkowl**
Fixes: [ARO-4744](https://issues.redhat.com/browse/ARO-4744)

We do this validation in the frontend, we shouldn't call it here as well.

### CODE REVIEW

**Comment by bennerv** [comment]
/lgtm 
/approve 

Change upstreamed here: https://github.com/openshift/installer/pull/7865

**Comment by bitoku** [comment]
I have a question.
Is the validation in the installer problematic for ARO?
Otherwise I don't want to add the new diff to the fork just because it is duplicate or not required.
The installer for ARO is already really complex and the more carry patches there are, the longer it takes to make a new release branch.

**Comment by tiguelu** [comment]
> I have a question. Is the validation in the installer problematic for ARO? Otherwise I don't want to add the new diff to the fork just because it is duplicate or not required. The installer for ARO is already really complex and the more carry patches there are, the longer it takes to make a new release branch.

This was done in our forked installer as a carry-patch because we needed to improve installation success rates on already released ARO branches. The change was also sent to upstream (and it will be dropped from our fork in future releases): https://github.com/openshift/installer/pull/7865 

In particular, it was made available from 4.16 (master at the time):
https://github.com/openshift/installer/blob/release-4.16/pkg/asset/installconfig/installconfig.go#L173

For 4.14 I think we are good to merge this PR, but **after** the latest work for 4.14 is merged in PR https://github.com/openshift/installer-aro/pull/15 (because it will require a forced-push, as a result of rebasing from upstream)

For 4.15, we can check with upstream if https://github.com/openshift/installer/pull/7865 can be backported to release-4.15, to try to drop the carry-patch before 4.16. If not feasible, we will drop it in 4.16

**Comment by tiguelu** [comment]
We rebased the target branch `release-4.14-azure` to bring changes from upstream, and reapply our ARO patches on top of it in PR https://github.com/openshift/installer-aro/pull/15. This would have required this PR to be reapplied on top of the new branch/patches (it was based on top of the previous aro patches committed in an older snapshot of upstream changes).

For the sake of simplicity, we have included the patch from this PR in `release-4.14-azure` branch with our existing process to cherry pick the patch from the previous aro release branch `release-4.13-azure`, and merged it under PR https://github.com/openshift/installer-aro/pull/19. Hence, this PR https://github.com/openshift/installer-aro/pull/4 can be just closed.

**Pull request closed without merging**
