### PR TITLE
Release 4.15 hacks

### PR DESCRIPTION
**Pull request by slintes**
This PR is adding the ARO hacks on top of the upstream 4.15 branch.

Additionally to what's documented in https://github.com/Azure/ARO-RP/blob/master/docs/upstream-differences.md, I also run `./hack/verify-vendor.sh` after each cherry pick, which resolved merge issues in `go.sum` and `modules.txt` nicely. For making vendoring faster, I added a new commit which skips running it for the terraform and CAPI modules, similar to what we have in `./hack/build.sh`, see https://github.com/openshift/installer-aro/commit/e67ab7b527ef934b2f96e8205a99214610d2ace5

I will create PR for https://github.com/Azure/ARO-RP/blob/master/docs/upstream-differences.md to document that vendoring should be run as well, if no one disagrees.

[ARO-6044](https://issues.redhat.com//browse/ARO-6044)

### CODE REVIEW

**Comment by slintes** [comment]
adding CI config for this branch here: https://github.com/openshift/release/pull/52620

**Comment by bitoku** [comment]
It might be better to have it reviewed along with the changes in `installer-aro-wrapper` and confirm if the cluster creation succeeds with the new 4.15 installer image.

Because of differences between normal OCP and ARO, you sometimes need to change some codes additionally.

Once you finished `installer-aro-wrapper` changes, you can test the installer image following https://github.com/Azure/ARO-RP/blob/master/docs/deploy-development-rp.md#use-a-custom-installer.

**Comment by tiguelu** [comment]
>     * dofinn       
>       * User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.
> 
>     * s-amann
>       * User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.
> 
>     * shivkumar13
>       * User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.

We will need to remove the 3 above usernames mentioned in the comment of openshift-ci bot, because they have left RH. 

Can you re-push the last CARRY PATCH that modifies the OWNERS file? We will review older release branches that are still active as we rebase them.

**Review by tiguelu — CHANGES_REQUESTED** [review]
Just needing to re-push the commit for the OWNERS file. Everything else looks great to me.

**Comment by slintes** [comment]
> Just needing to re-push the commit for the OWNERS file. Everything else looks great to me.

done :)

Can you also please lgtm and approve the CI config update, in order to run tests here? :)
https://github.com/openshift/release/pull/52620

**Review by tiguelu — APPROVED** [review]

**Pull request merged**
